version: "2"
volumes:
  letsencrypt-data:
    driver: local
  transmission-data:
    driver: local
  flexget-data:
    driver: local
services:
  nginx:
    image: michaelbaudino/nginx-letsencrypt-reverse-proxy
    depends_on: [transmission]
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - letsencrypt-data:/etc/letsencrypt/
    environment:
      BACKEND: "transmission:9091"
  transmission:
    image: dperson/transmission
    volumes:
      - transmission-data:/var/lib/transmission-daemon
    ports:
      - "5151:5151"
    environment:
      TRUSER: overrideme
      TRPASSWD: overrideme
      TR_PEER_PORT: 5151
      TR_ENCRYPTION: 2 # require encryption
      TR_PEER_LIMIT_GLOBAL: 4096
      TR_PEER_LIMIT_PER_TORRENT: 1024
      TR_UPLOAD_SLOTS_PER_TORRENT: 64
      TR_RATIO_LIMIT_ENABLED: "false"
  flexget:
    build: ./flexget
    depends_on:
      - transmission
    environment:
      TRANSMISSION_HOST: transmission
      TRANSMISSION_PORT: 9091
      TRANSMISSION_USERNAME: overrideme
      TRANSMISSION_PASSWORD: overrideme
      SHOWRSS_FEED_URL: "https://showrss.info/user/FEED_ID.rss?..."
    volumes:
      - flexget-data:/flexget
