version: "2"
volumes:
  transmission-data:
    driver: local
services:
  nginx:
    depends_on:
      - transmission
    environment:
      BACKEND: "transmission:9091"
  transmission:
    image: dperson/transmission
    volumes:
      - transmission-data:/var/lib/transmission-daemon
    ports:
      - "5151:5151"
    environment:
      TRUSER: overrideme
      TRPASSWD: overrideme
      TR_PEER_PORT: 5151
      TR_ENCRYPTION: 2 # require encryption
      TR_PEER_LIMIT_GLOBAL: 4096
      TR_PEER_LIMIT_PER_TORRENT: 1024
      TR_UPLOAD_SLOTS_PER_TORRENT: 64
      TR_RATIO_LIMIT_ENABLED: "false"
