tasks:
  ShowRSS:
    rss: '{{SHOWRSS_FEED_URL}}'
    all_series:
      propers: 1 hours
    transmission:
      host: {{TRANSMISSION_HOST}}
      port: {{TRANSMISSION_PORT}}
      username: '{{TRANSMISSION_USERNAME}}'
      password: '{{TRANSMISSION_PASSWORD}}'
      addpaused: no
  Cleanup:
    clean_transmission:
      host: {{TRANSMISSION_HOST}}
      port: {{TRANSMISSION_PORT}}
      username: '{{TRANSMISSION_USERNAME}}'
      password: '{{TRANSMISSION_PASSWORD}}'
      transmission_seed_limits: yes
      finished_for: 2 days
      min_ratio: 5
schedules:
  - tasks: [ShowRSS, Cleanup]
    interval:
      hours: 1
